### ISSUE TITLE
Can't Deploy to Heroku

### ISSUE THREAD

**Issue by uzegonemad** [rustyio/super-imap#3]
When I attempt to deploy to Heroku, I consistently get the error below.

I don't do much with Heroku so there could easily be something I'm missing. I've just been tapping the "Deploy to Heroku" button from the readme.

```
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.2.0
-----> Installing dependencies using 1.9.7
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching gem metadata from https://rubygems.org/........
       Fetching version metadata from https://rubygems.org/...
       Fetching dependency metadata from https://rubygems.org/..
       Fetching git://github.com/activeadmin/activeadmin.git
       Using rake 10.4.2
       Installing minitest 5.5.1
       Installing i18n 0.7.0
       Installing builder 3.2.2
       Installing thread_safe 0.3.4
       Installing rack 1.5.2
       Installing erubis 2.7.0
       Installing mime-types 2.4.3
       Installing sass 3.2.19
       Installing thor 0.19.1
       Installing coffee-script-source 1.8.0
       Installing execjs 2.2.2
       Installing formtastic_i18n 0.1.1
       Using bundler 1.9.7
       Installing arel 5.0.1.20140414130214
       Installing hike 1.2.3
       Installing multi_json 1.10.1
       Installing json 1.8.2
       Installing orm_adapter 0.5.0
       Installing tilt 1.4.1
       Installing dotenv-deployment 0.0.2
       Installing multipart-post 2.0.0
       Installing gibberish 1.4.0
       Installing jwt 1.2.0
       Installing multi_xml 0.5.5
       Installing netrc 0.10.2
       Installing oauth 0.4.7
       Installing bcrypt 3.1.9
       Installing rails_serve_static_assets 0.0.3
       Installing rails_stdout_logging 0.0.3
       Installing kgio 2.9.3
       Using rdoc 4.2.0
       Installing pg 0.17.1
       Installing tzinfo 1.2.2
       Installing rack-test 0.6.3
       Installing warden 1.2.3
       Installing mail 2.6.3
       Installing bourbon 3.2.4
       Installing coffee-script 2.3.0
       Installing raindrops 0.13.0
       Installing airbrake 4.1.0
       Installing uglifier 2.7.0
       Installing sprockets 2.12.3
       Installing dotenv 0.11.1
       Installing faraday 0.9.1
       Installing rest-client 1.7.2
       Installing rails_12factor 0.0.3
       Installing sdoc 0.4.1
       Installing activesupport 4.1.6
       Installing foreman 0.75.0
       Installing oauth2 0.9.4
       Installing actionview 4.1.6
       Installing arbre 1.0.3
       Installing activemodel 4.1.6
       Installing delayed_job 4.0.6
       Installing jbuilder 2.2.6
       Installing actionpack 4.1.6
       Installing activerecord 4.1.6
       Installing ruby-prof 0.15.6
       Installing actionmailer 4.1.6
       Installing railties 4.1.6
       Installing formtastic 3.1.3
       Installing has_scope 0.6.0.rc
       Installing kaminari 0.16.2
       Installing sprockets-rails 2.2.2
       Installing polyamorous 1.1.0
       Installing delayed_job_active_record 4.0.3
       Installing coffee-rails 4.0.1
       Installing responders 1.0.0
       Installing jquery-rails 3.1.2
       Installing jquery-ui-rails 5.0.3
       Installing rails 4.1.6
       Installing sass-rails 4.0.5
       Installing turbolinks 2.5.3
       Installing ransack 1.6.2
       Installing inherited_resources 1.4.1
       Installing devise 3.4.1
       Using activeadmin 1.0.0.pre from git://github.com/activeadmin/activeadmin.git (at 0becbef)
       Installing unicorn 4.8.3
       Bundle complete! 26 Gemfile dependencies, 79 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Bundle completed (83.76s)
       Cleaning up the bundler cache.
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       rake aborted!
       Must set ENCRYPTION_KEY environment variable.
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/config/environments/production.rb:80:in `block in <top (required)>'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/railties-4.1.6/lib/rails/railtie.rb:210:in `instance_eval'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/railties-4.1.6/lib/rails/railtie.rb:210:in `configure'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/config/environments/production.rb:1:in `<top (required)>'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/railties-4.1.6/lib/rails/engine.rb:594:in `block (2 levels) in <class:Engine>'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/railties-4.1.6/lib/rails/engine.rb:593:in `each'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/railties-4.1.6/lib/rails/engine.rb:593:in `block in <class:Engine>'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `instance_exec'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `run'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/railties-4.1.6/lib/rails/initializable.rb:55:in `block in run_initializers'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/railties-4.1.6/lib/rails/initializable.rb:44:in `each'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/railties-4.1.6/lib/rails/initializable.rb:44:in `tsort_each_child'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/railties-4.1.6/lib/rails/initializable.rb:54:in `run_initializers'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/railties-4.1.6/lib/rails/application.rb:300:in `initialize!'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/config/environment.rb:5:in `<top (required)>'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/railties-4.1.6/lib/rails/application.rb:276:in `require_environment!'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/railties-4.1.6/lib/rails/application.rb:389:in `block in run_tasks_blocks'
       /tmp/build_38fcae1d00bdf51ebfaf7c59cf7ba5f2/rustyio-super-imap-05bd728/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-2.2.2/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
       Tasks: TOP => environment
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app
```

**Comment by rustyio** [comment]
The system is looking for an `ENCRYPTION_KEY` environment variable. (There is an error message at the top of the stack trace saying **Must set ENCRYPTION_KEY environment variable.**)

I'm not sure how one should set this in a secure way while still providing a 'Deploy to Heroku' button. I may need to remove that button.

**Comment by raul** [comment]
The app.json Schema allows to generate random values for environment variables as described [here](https://devcenter.heroku.com/articles/app-json-schema#env).

You may want to add `SECRET_KEY_BASE` and `ENCRYPTION_KEY` to the `app.json` file, obtaining something like:

```
{
    "name": "SuperIMAP",
    "description": "Monitor inboxes for incoming email, at scale.",
    "repository": "https://github.com/rustyio/super-imap",
    "keywords": ["IMAP", "mail", "webhook", "client", "ruby"],
    "success_url": "/admin",
    "scripts": {
        "postdeploy": "bundle exec rake db:seed"
    },
    "addons": [
        "heroku-postgresql"
    ],
    "env": {
        "ENCRYPTION_KEY": {
          "description": "Used to encrypt information in the database.",
          "generator": "secret",
        },
        "SECRET_KEY_BASE": {
          "description": "A secret key for verifying the integrity of signed cookies.",
          "generator": "secret",
        }
    },
}
```

**Comment by rustyio** [comment]
Fixed. Thanks for the tip!
