### ISSUE TITLE
errors"=>[{"domain"=>"global", "reason"=>"notFound", "message"=>"Not Found"}

### ISSUE THREAD

**Issue by bacancy-gautam** [rustyio/super-imap#8]
Hello,
   I've set up this in my local machine but I'm getting this error
errors"=>[{"domain"=>"global", "reason"=>"notFound", "message"=>"Not Found"}
on callback url

Is it valid to check this on local or not?

**Comment by amitsavani** [comment]
I am not sure but I believe it's the same error. I get the error on callback after auth completes.

```ruby
OAuth2::Error (Not Found):
    /home/amit/.rvm/gems/ruby-2.2.4/gems/oauth2-0.9.4/lib/oauth2/client.rb:113:in `request'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/oauth2-0.9.4/lib/oauth2/access_token.rb:107:in `request'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/oauth2-0.9.4/lib/oauth2/access_token.rb:114:in `get'
    /home/amit/projects/testapp/super-imap/app/helpers/oauth2/connects_helper.rb:64:in `gmail_oauth2_email'
    /home/amit/projects/testapp/super-imap/app/helpers/oauth2/connects_helper.rb:59:in `oauth2_email'
    /home/amit/projects/testapp/super-imap/app/helpers/oauth2/connects_helper.rb:41:in `oauth2_callback_helper'
    /home/amit/projects/testapp/super-imap/app/controllers/users/base_callback_controller.rb:28:in `apply_helper'
    /home/amit/projects/testapp/super-imap/app/controllers/users/base_callback_controller.rb:21:in `callback'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:189:in `process_action'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activerecord-4.1.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/abstract_controller/base.rb:136:in `process'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionview-4.1.6/lib/action_view/rendering.rb:30:in `process'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_controller/metal.rb:196:in `dispatch'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_controller/metal.rb:232:in `block in action'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:82:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:50:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:73:in `block in call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:59:in `each'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:59:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:678:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/flash.rb:254:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/cookies.rb:560:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activerecord-4.1.6/lib/active_record/query_cache.rb:36:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activerecord-4.1.6/lib/active_record/migration.rb:380:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:82:in `run_callbacks'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/reloader.rb:73:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/airbrake-4.1.0/lib/airbrake/rails/middleware.rb:13:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/railties-4.1.6/lib/rails/rack/logger.rb:38:in `call_app'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/railties-4.1.6/lib/rails/rack/logger.rb:20:in `block in call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/tagged_logging.rb:26:in `tagged'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/tagged_logging.rb:68:in `tagged'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/railties-4.1.6/lib/rails/rack/logger.rb:20:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/activesupport-4.1.6/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/rack-1.5.2/lib/rack/lock.rb:17:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/actionpack-4.1.6/lib/action_dispatch/middleware/static.rb:64:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:16:in `_call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/airbrake-4.1.0/lib/airbrake/user_informer.rb:12:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/railties-4.1.6/lib/rails/engine.rb:514:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/railties-4.1.6/lib/rails/application.rb:144:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/rack-1.5.2/lib/rack/chunked.rb:43:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:576:in `process_client'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:536:in `maintain_worker_count'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:294:in `join'
    /home/amit/.rvm/gems/ruby-2.2.4/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
    /home/amit/.rvm/gems/ruby-2.2.4/bin/unicorn:23:in `load'
    /home/amit/.rvm/gems/ruby-2.2.4/bin/unicorn:23:in `<main>'
    /home/amit/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
    /home/amit/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
Redirected to http://localhost:5000/failure.html
```
